local config = require("autobarrel.config")
local fs = require("autobarrel.fs")
local util = require("autobarrel.util")

local M = {}

M._writing_lock = false

local function strip_extension(filename)
  return filename:gsub("%.[^.]+$", "")
end

local function build_export_path(filename)
  local stem = strip_extension(filename)
  return "./" .. stem
end

local function render_exports(dir)
  local lines = {}
  local files = fs.list_source_files(dir)

  for _, entry in ipairs(files) do
    table.insert(lines, string.format('export * from "%s";', build_export_path(entry.name)))
  end

  return table.concat(lines, "\n")
end

local function render_file(dir)
  local content = render_exports(dir)

  if content == "" then
    return "// Auto-generated by autobarrel.nvim (da_b1rmuda)\n"
  end

  return table.concat({
    "// Auto-generated by autobarrel.nvim (da_b1rmuda)",
    "// Do not edit manually unless you know what you are doing.",
    "",
    content,
    "",
  }, "\n")
end

function M.create(dir)
  dir = util.normalize(dir)

  if not util.is_dir(dir) then
    util.notify("Not a directory: " .. dir, vim.log.levels.ERROR)
    return false
  end

  local barrel_path = fs.barrel_path(dir)

  if util.is_file(barrel_path) then
    util.notify("Barrel already exists: " .. barrel_path, vim.log.levels.WARN)
    return false
  end

  return M.update(dir, { force_create = true })
end

function M.update(dir, opts)
  opts = opts or {}
  dir = util.normalize(dir)

  if not util.is_dir(dir) then
    util.notify("Not a directory: " .. dir, vim.log.levels.ERROR)
    return false
  end

  local barrel_path = fs.barrel_path(dir)
  local content = render_file(dir)

  M._writing_lock = true
  local ok, err = pcall(util.write_file, barrel_path, content)
  M._writing_lock = false

  if not ok then
    util.notify("Failed to write barrel: " .. tostring(err), vim.log.levels.ERROR)
    return false
  end

  if opts.force_create then
    util.notify("Created barrel: " .. barrel_path)
  else
    util.notify("Updated barrel: " .. barrel_path)
  end

  vim.schedule(function()
    pcall(vim.cmd, "silent! checktime")
  end)

  return true
end

function M.update_from_file(file_path)
  file_path = util.normalize(file_path)

  local filename = util.basename(file_path)
  local barrel_name = config.options.barrel_name

  if filename == barrel_name then
    return
  end

  if M._writing_lock then
    return
  end

  local opts = config.options

  if opts.update_only_nearest then
    local nearest = fs.find_nearest_parent_barrel(file_path)
    if nearest then
      M.update(util.dirname(nearest))
    end
    return
  end

  local barrels = fs.find_parent_barrels(file_path)
  for _, barrel_path in ipairs(barrels) do
    M.update(util.dirname(barrel_path))
  end
end

return M
